# Generated by Django 2.1.7 on 2019-06-01 12:38

import display.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Base ID UUID field', primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, help_text='The base desc field')),
                ('attrib', models.TextField(blank=True, help_text='The base attrib field')),
                ('order', models.IntegerField(default=0, help_text='Base Order Field')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('blue', 'Blue'), ('white', 'White'), ('black', 'Black'), ('grey', 'Grey')], default='red', help_text='The DisplayBase name field', max_length=8, unique=True)),
                ('r', models.IntegerField(default=128, help_text='Red Value')),
                ('g', models.IntegerField(default=0, help_text='Green Value')),
                ('b', models.IntegerField(default=0, help_text='Blue Value')),
                ('a', models.IntegerField(default=255, help_text='Alpha Value')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Base ID UUID field', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='The base name field', max_length=64)),
                ('desc', models.TextField(blank=True, help_text='The base desc field')),
                ('attrib', models.TextField(blank=True, help_text='The base attrib field')),
                ('order', models.IntegerField(default=0, help_text='Base Order Field')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('colour', models.ForeignKey(on_delete=models.SET(display.models.get_default_colour), to='display.Colour', to_field='name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Base ID UUID field', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='The base name field', max_length=64)),
                ('desc', models.TextField(blank=True, help_text='The base desc field')),
                ('attrib', models.TextField(blank=True, help_text='The base attrib field')),
                ('order', models.IntegerField(default=0, help_text='Base Order Field')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('x', models.FloatField(default=0, help_text='XPos Value')),
                ('y', models.FloatField(default=0, help_text='YPos Value')),
                ('z', models.FloatField(default=0, help_text='Zpos Value')),
                ('colour', models.ForeignKey(on_delete=models.SET(display.models.get_default_colour), to='display.Colour', to_field='name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Base ID UUID field', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='The base name field', max_length=64)),
                ('desc', models.TextField(blank=True, help_text='The base desc field')),
                ('attrib', models.TextField(blank=True, help_text='The base attrib field')),
                ('order', models.IntegerField(default=0, help_text='Base Order Field')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('x', models.FloatField(default=0, help_text='XPos Value')),
                ('y', models.FloatField(default=0, help_text='YPos Value')),
                ('z', models.FloatField(default=0, help_text='Zpos Value')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Base ID UUID field', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='The base name field', max_length=64)),
                ('desc', models.TextField(blank=True, help_text='The base desc field')),
                ('attrib', models.TextField(blank=True, help_text='The base attrib field')),
                ('order', models.IntegerField(default=0, help_text='Base Order Field')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('x', models.FloatField(default=0, help_text='XRot Value')),
                ('y', models.FloatField(default=0, help_text='YRot Value')),
                ('z', models.FloatField(default=0, help_text='ZRot Value')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Base ID UUID field', primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, help_text='The base desc field')),
                ('attrib', models.TextField(blank=True, help_text='The base attrib field')),
                ('order', models.IntegerField(default=0, help_text='Base Order Field')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('rect', 'Rectangle'), ('circle', 'Circle'), ('ellipse', 'Ellipse'), ('line', 'Line'), ('polyline', 'Polylone'), ('polygon', 'Polygon')], default='circle', help_text='The DisplayBase name field', max_length=8, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Base ID UUID field', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='The base name field', max_length=64)),
                ('desc', models.TextField(blank=True, help_text='The base desc field')),
                ('attrib', models.TextField(blank=True, help_text='The base attrib field')),
                ('order', models.IntegerField(default=0, help_text='Base Order Field')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('size', models.FloatField(default=1.0, help_text='The DisplayBase name field')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='node',
            name='shape',
            field=models.ForeignKey(on_delete=models.SET(display.models.get_default_shape), to='display.Shape', to_field='name'),
        ),
        migrations.AddField(
            model_name='link',
            name='node1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LinkNode1', to='display.Node'),
        ),
        migrations.AddField(
            model_name='link',
            name='node2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LinkNode2', to='display.Node'),
        ),
        migrations.AddField(
            model_name='link',
            name='shape',
            field=models.ForeignKey(on_delete=models.SET(display.models.get_default_shape), to='display.Shape', to_field='name'),
        ),
    ]
